CSV Exercise
AdaGold/csv-practice pull request #1
Opened 2018-08-10 22:19 UTC by CheezItMan

A CSV Practice Activity and later students will use the CSV data with enumerables to manipulate the given data.

2018-08-12 17:50 UTC, tildeee requested changes
I LOVE THIS! Particularly the tests you provided.

Also it's a great exercise; just implement three methods. It's great!

If this is a one-hour assignment, I actually would consider making some of Part 2 optional?

Lastly, you have a stray lock file in here: `data/.~lock.Sacramento...` to delete. Otherwise, I think it's fine to merge

2018-08-12 17:50 UTC, tildeee commented on README.md
> +In this exercise you are asked to process a CSV file with Olymic Games data.  This exercise has two parts.  The first allowing you to practice reading in data from a CSV file, processing it and writi
"Olymic Games" -> "Olympic Games" typo

2018-08-12 17:50 UTC, tildeee commented on README.md
> +In this exercise you are asked to process a CSV file with Olymic Games data.  This exercise has two parts.  The first allowing you to practice reading in data from a CSV file, processing it and writi
Grammar: "The first allowing you to ..." -> "The first part allows you to" or something similar, like, "In the first part, you will practice reading in data ..."

2018-08-13 15:15 UTC, CheezItMan commented
The idea is that it's a 2 parter with more practice using Enums later in the week.

2018-08-13 21:56 UTC, droberts-sea requested changes
Looks good, aside from spelling.

2018-08-13 21:56 UTC, droberts-ada commented on README.md
> +-    `country_with_most_metals(metal_totals)` - This method returns the country with the highest number of metals.
These should all be `medal` not `metal`

2018-08-14 22:37 UTC, Hamled reviewed
I think this looks good, with the changes suggested already by @tildeee and @droberts-ada.

One suggestion I would make for the README is to call out more specifically the data structures that will be used as input for each method.

You do a good job of making it clear that in Part 1 the input for `total_medals_per_country` is the output from `load_data` (and similarly for `save_medal_totals`). However, I think it would also be good to point them to the test suite because it also contains a description of the structure that `load_data` should return.

And for Part 2 it seems like, based on the parameter names, those input data structures are the same as the ones used/created in Part 1. If that is true then I think it would help to call that out more explicitly (e.g. saying that `medals_sorted_by_country` takes the same input as what `total_medals_per_country` returns).

2018-08-16 04:04 UTC, merged