Adding before blocks
AdaGold/csv-practice pull request #6
Opened 2019-08-21 18:24 UTC by dHelmgren

Theses got dropped, not sure why or how, but some systems don't work without them.

2019-08-21 20:36 UTC, kaidamasaki requested changes

2019-08-21 20:36 UTC, kaidamasaki commented on test/csv_practice_test.rb
> +      data = load_data(OLYMPIC_DATA_FILENAME)
Did you mean `@data`?  As written this doesn't work.

2019-08-21 20:36 UTC, kaidamasaki commented on test/csv_practice_test.rb
> +      data = load_data(OLYMPIC_DATA_FILENAME)
It also might make sense to use `let` here.

2020-02-14 22:18 UTC, CheezItMan commented
This one seems stale.

2020-02-14 22:18 UTC, closed without merging